name: Run tox tests with UV

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docker/**"
      - "frontend/**"
      - "docs/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths-ignore:
      - "docker/**"
      - "frontend/**"
      - "docs/**"

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.14"
          python-version: 3.12.9

      - name: Cache tox environments
        uses: actions/cache@v4
        with:
          path: .tox/
          key: ${{ runner.os }}-tox-uv-${{ hashFiles('**/pyproject.toml', '**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-uv-

      - name: Install tox with UV
        run: uv pip install tox tox-uv

      - name: Run tox
        id: tox
        run: |
          tox

      - name: Combine test reports
        if: always() && (hashFiles('runner-report.md') != '' || hashFiles('sdk1-report.md') != '')
        run: |
          bash .github/scripts/combine-test-reports.sh

      - name: Render combined test report to PR
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: always() && hashFiles('combined-test-report.md') != '' && github.event.pull_request.head.repo.fork == false
        with:
          header: test-results
          recreate: true
          path: combined-test-report.md

      - name: Output combined report to job summary
        if: always() && hashFiles('combined-test-report.md') != ''
        shell: bash
        run: |
          cat combined-test-report.md >> $GITHUB_STEP_SUMMARY
