name: Unstract Docker Image Build and Push (Development)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "latest"
      service_name:
        description: "Service to build"
        required: true
        default: "backend" # Provide a default value
        type: choice
        options: # Define available options
          - all-services
          - frontend
          - backend
          - document-service
          - platform-service
          - worker
          - prompt-service
          - x2text-service

run-name: "[${{ inputs.service_name }}] Docker Image Build and Push (Development)"

jobs:
  build-and-push:
    runs-on: custom-k8s-runner
    steps:
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image for the specified service
      - name: Build and push image for ${{ github.event.inputs.service_name }}
        working-directory: ./docker
        if: github.event.inputs.service_name != 'all-services'
        run: |
          VERSION=${{ github.event.inputs.tag }} docker compose -f docker-compose.build.yaml build --no-cache ${{ github.event.inputs.service_name }}
          docker push unstract/${{ github.event.inputs.service_name }}:${{ github.event.inputs.tag }}

      # Build and push all service images
      - name: Build and push all images
        working-directory: ./docker
        if: github.event.inputs.service_name == 'all-services'
        run: |
          VERSION=${{ github.event.inputs.tag }} docker-compose -f docker-compose.build.yaml build --no-cache
          # Push all built images
          docker push unstract/backend:${{ github.event.inputs.tag }}
          docker push unstract/frontend:${{ github.event.inputs.tag }}
          docker push unstract/document-service:${{ github.event.inputs.tag }}
          docker push unstract/platform-service:${{ github.event.inputs.tag }}
          docker push unstract/worker:${{ github.event.inputs.tag }}
          docker push unstract/prompt-service:${{ github.event.inputs.tag }}
          docker push unstract/x2text-service:${{ github.event.inputs.tag }}
